### ISSUE TITLE
How can I change admin password in docker?

### ISSUE THREAD

**Issue by qq253498229** [flowable/flowable-engine#1661]
I try to change the 'admin' password,but then I can not login except idm module.
how to resolved?

**Comment by qq253498229** [comment]
this is my docker-compose.yml

```
version: '3.6'
services:
  flowable:
    image: registry.cn-beijing.aliyuncs.com/codeforfun/all-in-one:latest
    environment:
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/flowable
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - FLOWABLE.REST.APP.ADMIN.USER-ID=rest-admin
      - FLOWABLE.REST.APP.ADMIN.PASSWORD=test1
      - FLOWABLE.REST.APP.ADMIN.FIRST-NAME=Rest
      - FLOWABLE.REST.APP.ADMIN.LAST-NAME=Admin
      - FLOWABLE.IDM.APP.ADMIN.USER-ID=admin
      - FLOWABLE.IDM.APP.ADMIN.PASSWORD=test1
      - FLOWABLE_COMMON_APP_IDM-URL=http://localhost:8080/flowable-idm
      - FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://flowable.codeforfun.cn/flowable-idm
      - FLOWABLE_COMMON_APP_IDM-ADMIN.USER=admin
      - FLOWABLE_COMMON_APP_IDM-ADMIN.PASSWORD=test1
    ports:
      - 80:8080
  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - './data/mysql:/var/lib/mysql'
      - './config/mysql:/etc/mysql/conf.d'
```
