### ISSUE TITLE
Docker: Unable to customise port number

### ISSUE THREAD

**Issue by srinathganesh** [flowable/flowable-engine#1719]
Say port 8080 is not available and we would like change it, since we are deploying it via docker we could do this

```
services:
  flowable:
    image: flowable/all-in-one
    ports:
      - 1111:8080
```

But when I visit the url
`http://localhost:1111/flowable-modeler/`

it redirects me to the url
`http://localhost:8080/flowable-idm/#/login?redirectOnAuthSuccess=true&redirectUrl=http://localhost:1111/flowable-modeler/`

looks like its been hard-coded to 8080
