### ISSUE TITLE
docker: flowable-admin env variables for SERVER-CONFIG_... does not rewrited on admin-ui configuration page after changes

### ISSUE THREAD

**Issue by ikusmart** [flowable/flowable-engine#2045]
### Describe the bug
Hello.
When I run the flowable-admin by docker-compose file for the first time, I initialize the variables for SERVER_CONFIG with the following values:
```
...  #describe flowable-rest api container
flowable:
    container_name: flowable
    environment:
     ... #describe flowable rest envs
    ports:
      - port1:8080
    
... #describe flowable-admin container
  flowable-admin-app:
    image: flowable/flowable-admin
    environment:
       ... #other envs for flowable-admin 
        - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_SERVER-ADDRESS=http://process-address-old-host
        - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_PORT=port1

```
And everything works fine.

But if I try to change the values of these env variables in the docker-compos file (for example from http://process-address-old-host to http://process-address-new-host or from _port1_ to _port2_), after restarting the containers in the admin interface the addresses remain unchanged (by `docker-compose up` or `docker-compose up --build` commands)

Also i don't understand, how can i set login and password for rest-api in flowable-admin-app section in docker-compose (for login to http://process-address-new-host)

### Expected behavior
After restart docker-compose new variables will appear in the flowable-admin
