### ISSUE TITLE
Swagger validation Error - operationId is repeated

### ISSUE THREAD

**Issue by erbg** [flowable/flowable-engine#2287]
**Describe the bug**
The swaggerfile /flowable-rest/docs/specfile/process/flowable.json has duplicated operationId defined and fails the validation.

**Expected behavior**
Validation of the swagger json should complete

**Code**
https://github.com/flowable/flowable-engine/blob/master/docs/public-api/references/swagger/process/flowable-swagger-process.yaml
```yaml
/management/batches/{batchId}/batch-parts:
    get:
      tags:
      - "Batches"
      summary: "List batch parts"
      description: ""
      **operationId: "listBatches"**
```
```yaml
/management/batches:`
    get:
      tags:
      - "Batches"
      summary: "List batches"
      description: ""
      **operationId: "listBatches"**
```
Duplicated OperationIds:
- listBatches
- deleteJob
- changeActivityState
- getTaskForm

**Additional context**
Flowable 6.51
